### ISSUE TITLE
Rename the package to lunar-json-api to prevent confusion.

### ISSUE THREAD

**Issue by tdwesten** [dystcz/lunar-api#16]
There is also a rest api package called `lunar-api` (see: https://github.com/SrPatinhas/lunar-api) so to prevent confusion its maybe smart to rename this package to `lunar-json-api`. 

What doe you think @theimerj?

**Comment by theimerj** [comment]
Let me think about it. The mentioned repo is an application, not even a package. I currently do not see much confusion in the naming. We may revisit in the future if it becomes a problem.
