### ISSUE TITLE
New cart created with every "add to cart" action

### ISSUE THREAD

**Issue by theimerj** [dystcz/lunar-api#18]
@tdwesten could you please help me with the assignment? Do you think you can describe a reproducible scenario for us to try? Thank you very much.

**Comment by tdwesten** [comment]
The situation we experience (without Redis) is that every time we call the `api/v1/carts/-actions/my-cart` endpoint, a new cart is created. This is with the lunar setting `'auto_create' => true`. I have now solved this in our situation with the [TokenBasedCartSessionMiddleware](https://github.com/dystcz/lunar-api/blob/main/src/Routing/Middleware/TokenBasedCartSessionMiddleware.php) to add a state to the cart in the middleware based on an `X-Cart-Token`.

I am open to other solutions but I think it would be nice to manage the cart state in the frontend.

**Comment by theimerj** [comment]
I don't know if this helps, but when I was creating the request collection in Postman, I had to add `Referer` header which is listed in sanctum stateful domains. After that it kept the "current cart" state without a problem.

**Comment by tdwesten** [comment]
I attempted the following command to make a request:

```bash
curl "https://api.monoz.test/api/v1/carts/-actions/my-cart?include=cart_lines.purchasable.product.default_url" \
     -H 'Content-Type: application/vnd.api+json' \
     -H 'Referer: https://api.monoz.test'
```

However, with each request, I receive a new cart ID.

**Comment by theimerj** [comment]
Hey, I looked into it. You have to ensure that the cart id can be retrieved from session. That is the way lunar handles carts. See: [CartSessionManager](https://github.com/lunarphp/lunar/blob/68398b1920627e18051bc4d6a85bd52ab8408144/packages/core/src/Managers/CartSessionManager.php#L29).

When using sanctum, you have to ensure that you have `SANCTUM_STATEFUL_DOMAINS=localhost`, it would be `monoz.test` in your case I presume.

But I am not sure if you use Sanctum or if sessions are utilized in your case. If not, you will have to create your own implementation of [CartSessionInterface](https://github.com/lunarphp/lunar/blob/68398b1920627e18051bc4d6a85bd52ab8408144/packages/core/src/Base/CartSessionInterface.php#L10), possibly with token based state.

In your case the `$cartId` is not found and new cart instance is created on every endpoint hit.

**Comment by theimerj** [comment]
I am closing this issue, because this is more related to Lunar functionality instead of the API.

However, I will put some care into cart handling as outlined here: https://github.com/dystcz/lunar-api/issues/93
