### ISSUE TITLE
Maintain Lunar consistency in field naming

### ISSUE THREAD

**Issue by tdwesten** [dystcz/lunar-api#20]
I think it is good to stay as close to Lunar as possible when naming fields. For example, the field `lines` on the cart causes confusion for me because I expected `cart-lines`. This also applies to `addresses` and `cart-addresses`. What do you think @dominik-wbz and @theimerj?

**Comment by theimerj** [comment]
Hey @tdwesten, you are right. I will rename the relations to make it more consistent.
