### ISSUE TITLE
Ability to Override (Order and Orderline) Policies

### ISSUE THREAD

**Issue by tdwesten** [dystcz/lunar-api#24]
Hi,

I would like to be able to override the policy for orders and orderlines so that I can sync order data with our ERP system.

Does it seem now that I have to rewrite the entire routeGroup, is that correct? Or is there another way?

**Comment by theimerj** [comment]
Hey @tdwesten, I think it should be possible to overwrite policies by registering them again in your application. Have you tried this approach?

**Comment by theimerj** [comment]
> Hi,
> 
> I would like to be able to override the policy for orders and orderlines so that I can sync order data with our ERP system.
> 
> Does it seem now that I have to rewrite the entire routeGroup, is that correct? Or is there another way?

Hey @tdwesten, you can register your own policies like so in your application SP:

```php
$this->booting(function () {
    Gate::policy(\Lunar\Models\Product::class, \Domain\Products\Policies\ProductPolicy::class);
});
```

Closing this issue, because it does not seem to be a problem after testing it in my app.
