### ISSUE TITLE
How to use your own schema/How to extend a schema

### ISSUE THREAD

**Issue by tdwesten** [dystcz/lunar-api#25]
I faced challenges while extending the productSchema for Algolia search implementation with facets. To overwrite the ProductSchema, follow these steps:

1. Replace the default `ProductSchema` in the `lunar-api.php` config file with your extended productSchema.
2. Add a custom JsonAPi server under `additional_servers`.
3. Define your `ProductSchema` in the `allSchemas()` function.

**Comment by theimerj** [comment]
You can have a look [here](https://github.com/dystcz/lunar-api-reviews/blob/03a198e7e30897ccbe541c17258fd1e61f6260fc/src/LunarReviewsServiceProvider.php#L92). There you can see how to extend Schemas in a package.

It should work the same way in your main application.

This will get documented in the future. But the actual implementation may be changed in the meantime. There are still some things to consider.

**Comment by tdwesten** [comment]
Apologies, the correct steps to perform this task are still unclear for me.
