### ISSUE TITLE
filter by product_type

### ISSUE THREAD

**Issue by thongnguyenau** [dystcz/lunar-api#59]
fetch this endpoint {{base_url}}/products?filter[product_type]=1

having this error below:
"message": "Relationship productType does not exist on resource schema products.",

**Comment by tdwesten** [comment]
Hi @thongnguyenau I have looked into it and added a fix to https://github.com/dystcz/lunar-api/pull/64. Additionally, the URL you are calling is not correct, it should be `api/v1/products?filter[product_type][id][]=1`

**Comment by thongnguyenau** [comment]
legend! thanks for your help with this. just tested and working as expected. waiting for the merge!

Much appreciated!
