### ISSUE TITLE
Working with Lunar model override (ModelManifest)

### ISSUE THREAD

**Issue by mtx-z** [dystcz/lunar-api#89]
Hello,

I'm using the "Lunar way" to override some Lunar models (using the [ModelManifest](https://docs.lunarphp.io/core/extending/models.html#extendable-models)). I need to add some media collection and custom methods to models. 

From the lunar-api package, I tried to play with the `domains.php` config file. But I always encounter Type issues (eg `TypeError: Dystcz\LunarApi\Domain\Collections\Policies\CollectionPolicy::viewProducts(): Argument #2 ($collection) must be of type Dystcz\LunarApi\Domain\Collections\Models\Collection, App\Models\Lunar\Collection given, called i`).

Of course, I tried to override more and more of the domains.php file to see if I could make something work but was not able to. 
During my tests, I also noticed that editing `domains.php` config file made my morph foreign key invalid (on URLs or Medias). I needed to set my custom model path as foreign keys to have my data displayed in the hub. Something that should [not be needed](https://discord.com/channels/497326121441034240/1090267962050629784/1201580222466760704) with lunar). 

Commenting the ModelManifest code in my AppServiceProvider (so my Lunar models override), results in all the lunar-api routes working as expected. 

It seems many lunar-api files are using the default Lunar models namespace. Would it be better if all were related to the domains.php config file? I could try to work something if it's the way to go.

**Comment by mtx-z** [comment]
Hi @theimerj,

thank you for your answer. 
I'm not sure I get it, here's what I've done :

```
$models = collect([
       \Lunar\Models\Product::class            => \App\Models\Lunar\Product::class,
        ...
]);
ModelManifest::register($models);
```

Then in `domains.php`
```
'products' => [
    ...
     'lunar_model' => \App\Models\Lunar\Product::class,
    ...
],
```

It seems to me that I'm swapping the Lunar Models to mine.

**Comment by theimerj** [comment]
Hi @mtx-z, yes, this looks good. Do you have an example repo? Could you list steps to reproduce the issue?

It is still a bit vague to me right now, I would have to try it out myself in order to help you.

**Comment by mtx-z** [comment]
Hi @theimerj,

I created a test repository here: https://github.com/mtx-z/lunar-api-test 
The last commit is about model swapping. 

I test on the `/products` (and I include `thumbnail,images,prices,cheapest_variant`) route. 
API works fine until I start to swap models. 

- When I have swap on domains.php + ModelManifest: I got a 401 Unauthenticated errors. Think a gate is failing.
- When I have swap on domains.php only (or manifest only): I got `Call to undefined relationship [cheapestVariant] on model [Lunar\\Models\\Product].` (added by lunar-api)

**Comment by theimerj** [comment]
Hey @mtx-z, I will get to it over the weekend. But at first glance I can see, that you are extending Lunar models and not Lunar API models. It makes sense that the functionality is missing then.

I will keep you posted after I get to it.

**Comment by mtx-z** [comment]
Ho, so I misunderstood you. I'll try to only swap lunar API ones (and extend them from my custom models). Thank you a lot!

**Comment by mtx-z** [comment]
Hi @theimerj;

please do not hesitate if I can help you on this. 

Best regards.

**Comment by theimerj** [comment]
Hey @mtx-z I created a PR (https://github.com/mtx-z/lunar-api-test/pull/1) to your test repo and now the extension seems to work. The changes are self-explanatory I think.

Let me know if you have any other issues.

**Comment by theimerj** [comment]
Hello @mtx-z, were you able to resolve the issues?

**Comment by mtx-z** [comment]
Hi @theimerj, I'm sorry for getting back to you so late. 

I made a small test case and it works as expected. I need to make extended tests on my "real world" project, but I'm on something else atm. 

This issue can be closed. I'll report back here if I encounter another related problem. 

Thank you again.
